/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/creditos` | `/creditos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/materia/clase`; params?: Router.UnknownInputParams; } | { pathname: `/profesor/crear`; params?: Router.UnknownInputParams; } | { pathname: `/profesor/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/materia/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pago/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/sala/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/creditos` | `/creditos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/materia/clase`; params?: Router.UnknownOutputParams; } | { pathname: `/profesor/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/profesor/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/materia/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/pago/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/sala/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buscar${`?${string}` | `#${string}` | ''}` | `/buscar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/creditos${`?${string}` | `#${string}` | ''}` | `/creditos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/materia/clase${`?${string}` | `#${string}` | ''}` | `/profesor/crear${`?${string}` | `#${string}` | ''}` | `/profesor/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/creditos` | `/creditos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/materia/clase`; params?: Router.UnknownInputParams; } | { pathname: `/profesor/crear`; params?: Router.UnknownInputParams; } | { pathname: `/profesor/dashboard`; params?: Router.UnknownInputParams; } | `/materia/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pago/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/sala/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/materia/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pago/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/sala/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
